apiVersion: multinic.example.com/v1alpha1
kind: MultiNicOperator
metadata:
  name: multinic-operator-scheduled
  namespace: multinic-system
spec:
  controller:
    image: multinic:v1alpha1
    replicas: 1
    resources:
      cpu: "100m"
      memory: "128Mi"
    healthProbe:
      port: 8082
      path: "/healthz"
  
  database:
    enabled: true
    image: mariadb:10.11
    storageSize: "10Gi"
    resources:
      cpu: "200m"
      memory: "256Mi"
    credentials:
      rootPassword: "cloud1234"
      database: "multinic"
      user: "multinic"
      password: "cloud1234"
  
  protection:
    enableMutationPrevention: true
    enableAutoRecovery: true
    allowedOperations:
    - "get"
    - "list"
    - "watch"
  
  reconcileTrigger:
    mode: "scheduled"
    interval: "180s"  # Reconcile every 3 minutes
    immediateOnCRChange: true  # But still respond immediately to CR changes
    timezone: "UTC" 