//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	out.Resources = in.Resources
	out.HealthProbe = in.HealthProbe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCredentials) DeepCopyInto(out *DBCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCredentials.
func (in *DBCredentials) DeepCopy() *DBCredentials {
	if in == nil {
		return nil
	}
	out := new(DBCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	out.Resources = in.Resources
	out.Credentials = in.Credentials
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthProbeConfig) DeepCopyInto(out *HealthProbeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthProbeConfig.
func (in *HealthProbeConfig) DeepCopy() *HealthProbeConfig {
	if in == nil {
		return nil
	}
	out := new(HealthProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNicOperator) DeepCopyInto(out *MultiNicOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNicOperator.
func (in *MultiNicOperator) DeepCopy() *MultiNicOperator {
	if in == nil {
		return nil
	}
	out := new(MultiNicOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiNicOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNicOperatorList) DeepCopyInto(out *MultiNicOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiNicOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNicOperatorList.
func (in *MultiNicOperatorList) DeepCopy() *MultiNicOperatorList {
	if in == nil {
		return nil
	}
	out := new(MultiNicOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiNicOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNicOperatorSpec) DeepCopyInto(out *MultiNicOperatorSpec) {
	*out = *in
	out.Controller = in.Controller
	out.Database = in.Database
	out.OpenStack = in.OpenStack
	in.Protection.DeepCopyInto(&out.Protection)
	out.ReconcileTrigger = in.ReconcileTrigger
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNicOperatorSpec.
func (in *MultiNicOperatorSpec) DeepCopy() *MultiNicOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(MultiNicOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNicOperatorStatus) DeepCopyInto(out *MultiNicOperatorStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	in.ControllerStatus.DeepCopyInto(&out.ControllerStatus)
	in.DatabaseStatus.DeepCopyInto(&out.DatabaseStatus)
	in.ProtectionStatus.DeepCopyInto(&out.ProtectionStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNicOperatorStatus.
func (in *MultiNicOperatorStatus) DeepCopy() *MultiNicOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(MultiNicOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfo) DeepCopyInto(out *NetworkInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfo.
func (in *NetworkInfo) DeepCopy() *NetworkInfo {
	if in == nil {
		return nil
	}
	out := new(NetworkInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackConfig) DeepCopyInto(out *OpenStackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackConfig.
func (in *OpenStackConfig) DeepCopy() *OpenStackConfig {
	if in == nil {
		return nil
	}
	out := new(OpenStackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCredentials) DeepCopyInto(out *OpenStackCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCredentials.
func (in *OpenStackCredentials) DeepCopy() *OpenStackCredentials {
	if in == nil {
		return nil
	}
	out := new(OpenStackCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackConfig) DeepCopyInto(out *OpenstackConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackConfig.
func (in *OpenstackConfig) DeepCopy() *OpenstackConfig {
	if in == nil {
		return nil
	}
	out := new(OpenstackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenstackConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackConfigList) DeepCopyInto(out *OpenstackConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenstackConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackConfigList.
func (in *OpenstackConfigList) DeepCopy() *OpenstackConfigList {
	if in == nil {
		return nil
	}
	out := new(OpenstackConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenstackConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackConfigSpec) DeepCopyInto(out *OpenstackConfigSpec) {
	*out = *in
	if in.VMNames != nil {
		in, out := &in.VMNames, &out.VMNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackConfigSpec.
func (in *OpenstackConfigSpec) DeepCopy() *OpenstackConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenstackConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackConfigStatus) DeepCopyInto(out *OpenstackConfigStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.VMNetworkInfos != nil {
		in, out := &in.VMNetworkInfos, &out.VMNetworkInfos
		*out = make([]VMNetworkInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackConfigStatus.
func (in *OpenstackConfigStatus) DeepCopy() *OpenstackConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OpenstackConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectionConfig) DeepCopyInto(out *ProtectionConfig) {
	*out = *in
	if in.AllowedOperations != nil {
		in, out := &in.AllowedOperations, &out.AllowedOperations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectionConfig.
func (in *ProtectionConfig) DeepCopy() *ProtectionConfig {
	if in == nil {
		return nil
	}
	out := new(ProtectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectionStatus) DeepCopyInto(out *ProtectionStatus) {
	*out = *in
	in.LastProtectionEvent.DeepCopyInto(&out.LastProtectionEvent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectionStatus.
func (in *ProtectionStatus) DeepCopy() *ProtectionStatus {
	if in == nil {
		return nil
	}
	out := new(ProtectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconcileTriggerConfig) DeepCopyInto(out *ReconcileTriggerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconcileTriggerConfig.
func (in *ReconcileTriggerConfig) DeepCopy() *ReconcileTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(ReconcileTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMNetworkInfo) DeepCopyInto(out *VMNetworkInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMNetworkInfo.
func (in *VMNetworkInfo) DeepCopy() *VMNetworkInfo {
	if in == nil {
		return nil
	}
	out := new(VMNetworkInfo)
	in.DeepCopyInto(out)
	return out
}
