apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-ssl
data:
  server-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDITCCAgmgAwIBAgIUB3bk+JgZC7/jZqBQHH6LTAswsFswDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVTXlTUUwgU2VydmVyIENBIENlcnQwHhcNMjMwNTI2MDYw
    MDAwWhcNMjQwNTI1MDYwMDAwWjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9QwwqIlJHWZKJFZI1ZmFz3Q3QZ3Xj
    Y3LmXYJ1ZWQxK1bXmQ5F5B5YUvJvH5OJxZZ6PlQwDQYJKoZIhvcNAQELBQADggEB
    AJwE0tJ5uZzwqBqYJidHHdb8FkzHU5yAR5jD84eS1PWk9Yk7QeJkITjEqbOKR5Kq
    K1bD4X5m7S5+1RQA8XqbRRhK6C3x9G9lCOjk4Y8/5D5V5GUTqgb6kxxk0D6pQPuX
    -----END CERTIFICATE-----
  server-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAvUMMKiJSR1mSiRWSNWZhc90N0Gd142Ny5l2CdWVkMStW15kO
    ReQeWFLybx+TicWWej5UMA0GCSqGSIb3DQEBCwUAA4IBAQCcBNLSebmc8KgamCYn
    Rx3W/BZMx1OcgEeYw/OHktT1pPWJO0HiZCE4xKmzikeSqitWw+F+Zu0uftUUAPF6
    m0UYSugt8fRvZQjo5OGPPyQ+VeRlE6oG+pMcZNA+qUD7l5nwqBqYJidHHdb8FkzH
    -----END RSA PRIVATE KEY-----
  ca-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIUB3bk+JgZC7/jZqBQHH6LTAswsFswDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVTXlTUUwgU2VydmVyIENBIENlcnQwHhcNMjMwNTI2MDYw
    MDAwWhcNMjQwNTI1MDYwMDAwWjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9QwwqIlJHWZKJFZI1ZmFz3Q3QZ3Xj
    Y3LmXYJ1ZWQxK1bXmQ5F5B5YUvJvH5OJxZZ6PlQwDQYJKoZIhvcNAQELBQADggEB
    AJwE0tJ5uZzwqBqYJidHHdb8FkzHU5yAR5jD84eS1PWk9Yk7QeJkITjEqbOKR5Kq
    K1bD4X5m7S5+1RQA8XqbRRhK6C3x9G9lCOjk4Y8/5D5V5GUTqgb6kxxk0D6pQPuX
    -----END CERTIFICATE----- 