---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multinic-protection
  failurePolicy: Fail
  name: vprotection.multinic.example.com
  rules:
  - apiGroups:
    - apps
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    - DELETE
    resources:
    - deployments
    - statefulsets
    - services
  sideEffects: None
