apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multinic-system

resources:
- ../rbac
# - ../manager  # Operator 패턴에서는 manager를 직접 배포하지 않음
- operator-deployment.yaml
- operator-service-account.yaml
- operator-role.yaml
- operator-role-binding.yaml
- multinic-operator-cr.yaml

patchesStrategicMerge:
- operator-manager-patch.yaml