apiVersion: apps/v1
kind: Deployment
metadata:
  name: multinic-operator
  namespace: multinic-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: OPERATOR_MODE
          value: "true"
        - name: WEBHOOK_ENABLED
          value: "true" 