apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multinic-operator-role
rules:
# MultiNicOperator permissions
- apiGroups:
  - multinic.example.com
  resources:
  - multinicoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multinic.example.com
  resources:
  - multinicoperators/finalizers
  verbs:
  - update
- apiGroups:
  - multinic.example.com
  resources:
  - multinicoperators/status
  verbs:
  - get
  - patch
  - update

# Managed resource permissions
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Health check permissions
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch

# Leader election permissions
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch 